name        = "Cocoabutter (forked from Cocoa)"
license     = "MIT"
licenselink = "https://github.com/nishanths/cocoa-hugo-theme/blob/master/LICENSE"
description = "Consistent, responsive theme with clean typography"
homepage    = "https://github.com/vickylaiio/cocoabutter-hugo-theme"
tags        = ["open-sans", "minimal", "clean", "svg", "comments"]
features    = ["blog", "responsive", "404", "icons", "disqus", "metadata"]
min_version = 0.18

[author]
  name      = "Vicky Lai"
  homepage  = "https://github.com/vickylaiio"
